require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ActiveChatsController do

  # This should return the minimal set of attributes required to create a valid
  # ActiveChat. As you add validations to ActiveChat, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ActiveChatsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all active_chats as @active_chats" do
      active_chat = ActiveChat.create! valid_attributes
      get :index, {}, valid_session
      assigns(:active_chats).should eq([active_chat])
    end
  end

  describe "GET show" do
    it "assigns the requested active_chat as @active_chat" do
      active_chat = ActiveChat.create! valid_attributes
      get :show, {:id => active_chat.to_param}, valid_session
      assigns(:active_chat).should eq(active_chat)
    end
  end

  describe "GET new" do
    it "assigns a new active_chat as @active_chat" do
      get :new, {}, valid_session
      assigns(:active_chat).should be_a_new(ActiveChat)
    end
  end

  describe "GET edit" do
    it "assigns the requested active_chat as @active_chat" do
      active_chat = ActiveChat.create! valid_attributes
      get :edit, {:id => active_chat.to_param}, valid_session
      assigns(:active_chat).should eq(active_chat)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ActiveChat" do
        expect {
          post :create, {:active_chat => valid_attributes}, valid_session
        }.to change(ActiveChat, :count).by(1)
      end

      it "assigns a newly created active_chat as @active_chat" do
        post :create, {:active_chat => valid_attributes}, valid_session
        assigns(:active_chat).should be_a(ActiveChat)
        assigns(:active_chat).should be_persisted
      end

      it "redirects to the created active_chat" do
        post :create, {:active_chat => valid_attributes}, valid_session
        response.should redirect_to(ActiveChat.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved active_chat as @active_chat" do
        # Trigger the behavior that occurs when invalid params are submitted
        ActiveChat.any_instance.stub(:save).and_return(false)
        post :create, {:active_chat => { "user" => "invalid value" }}, valid_session
        assigns(:active_chat).should be_a_new(ActiveChat)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ActiveChat.any_instance.stub(:save).and_return(false)
        post :create, {:active_chat => { "user" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested active_chat" do
        active_chat = ActiveChat.create! valid_attributes
        # Assuming there are no other active_chats in the database, this
        # specifies that the ActiveChat created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ActiveChat.any_instance.should_receive(:update).with({ "user" => "" })
        put :update, {:id => active_chat.to_param, :active_chat => { "user" => "" }}, valid_session
      end

      it "assigns the requested active_chat as @active_chat" do
        active_chat = ActiveChat.create! valid_attributes
        put :update, {:id => active_chat.to_param, :active_chat => valid_attributes}, valid_session
        assigns(:active_chat).should eq(active_chat)
      end

      it "redirects to the active_chat" do
        active_chat = ActiveChat.create! valid_attributes
        put :update, {:id => active_chat.to_param, :active_chat => valid_attributes}, valid_session
        response.should redirect_to(active_chat)
      end
    end

    describe "with invalid params" do
      it "assigns the active_chat as @active_chat" do
        active_chat = ActiveChat.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ActiveChat.any_instance.stub(:save).and_return(false)
        put :update, {:id => active_chat.to_param, :active_chat => { "user" => "invalid value" }}, valid_session
        assigns(:active_chat).should eq(active_chat)
      end

      it "re-renders the 'edit' template" do
        active_chat = ActiveChat.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ActiveChat.any_instance.stub(:save).and_return(false)
        put :update, {:id => active_chat.to_param, :active_chat => { "user" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested active_chat" do
      active_chat = ActiveChat.create! valid_attributes
      expect {
        delete :destroy, {:id => active_chat.to_param}, valid_session
      }.to change(ActiveChat, :count).by(-1)
    end

    it "redirects to the active_chats list" do
      active_chat = ActiveChat.create! valid_attributes
      delete :destroy, {:id => active_chat.to_param}, valid_session
      response.should redirect_to(active_chats_url)
    end
  end

end
